#!/bin/bash
## TechAlchemist (git.io/vddbF) ##
## AutoMiner Service ## Ubuntu 16.04 ##

[[ `id -u` == "0" ]] || { printf "[-] Run from root / sudo." ; exit 1 ; }
. /opt/tech-alchemist/crypto_ops/confs/crypto_vars.conf
coindir="/home/${cryptoname}" ; binsdir="${coindir}/binaries"
core_host="$miner_daemon_host" ; core_port="$miner_daemon_port"

if [ ! -d "${binsdir}" ] ; then
    printf "[/] Setting Core System \n"
    rm -rf "/root/.$cryptoname" "${coindir}/.$cryptoname"
    mkdir -p "${coindir}/blocks" "${coindir}/logs"
    cd ${coindir} 
    git clone "$binary_git_source" "${binsdir}"  || exit 1
    cd ${binsdir}
    find . -maxdepth 1 -exec chmod 755 {} \;
    printf "[+] Configured \n"
fi ; cd ${binsdir}

is_required()
{
 if [ "${miner_need}" != "true" ] ; then
  printf "[-] Miner for %s is not configured on this machine.\n    Check crypto_vars.conf :/\n" ${cryptoname}
  exit 1 
 fi
}

core_check()
{
  nc -vzw 1 ${core_host} ${core_port} &> /dev/null || {
  printf "[-] %s CoreRPC isn't listening @ %s:%d \n" "${cryptoname}" "${core_host}" "${core_port}"
  exit 1 ; }
}

start_miner(){
threads="$((`nproc`-1))"
printf "[/] Starting Miner \n"
${binsdir}/miner --threads $threads --address ${miner_address} \
  --daemon-address "${core_host}:${core_port}" \
  --log-level 4 >> "${logsdir}/minerjob.log" &
printf "[+] Started with Threads = %d \n" $threads
}

stop_miner()
{
printf "[/] Stopping Miner \n"
sudo kill -9 `sudo lsof +D . | grep "miner" | awk '{print $2}'` &> /dev/null
printf "[+] Stopped \n"
}

is_required
core_check
stop_miner
sleep 2
if [ ! -z "$miner_address" ] ; then
start_miner
else
printf "[-] Whereis Miner address \n    Check crypto_vars.conf \n"
exit 1
fi

exit 0
## E O F ##